### ISSUE TITLE
Gradle 6 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [kordamp/jdeprscan-gradle-plugin#5] opened 2019-10-21 21:50 UTC
Running `jdeprscan` under Gradle 6 yields the following warnings (the last three are multiplied for each source set I have):

```
Property 'consoleOutput' has redundant getters: 'getConsoleOutput()' and 'isConsoleOutput()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'forRemoval' has redundant getters: 'getForRemoval()' and 'isForRemoval()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'verbose' has redundant getters: 'getVerbose()' and 'isVerbose()'. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
The someSourceSetCompileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the someSourceSetCompileClasspath configuration instead.
The someSourceSetCompile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the someSourceSetCompileClasspath configuration instead.
The someSourceSetRuntime configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the someSourceSetRuntimeClasspath configuration instead.
```

**Comment by aalmiray** [comment] 2019-10-23 10:45
Hmm, it's easy to fix the configuration problem however the "redundant" getters are automatically generated by the Groovy compiler. According to the Gradle guide https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_annotations and I quote

    Annotations must be placed on getters or on Groovy properties. 
    Annotations placed on setters, or on a Java field without a corresponding annotated getter are ignored.

The aforementioned properties in the report are defined as

    @Input boolean forRemoval = false
    @Input boolean verbose = false
    @Input boolean consoleOutput = true

A workaround would be to manually define public getter & setter for a matching private boolean field, just like it's done in Java. This of course negates one of the advantages of using Groovy conventions.

@melix @ljacomet @wolfs Any clue why Gradle 6 now flags what used to be valid Groovy bytecode?

**Comment by wolfs** [comment] 2019-10-23 11:37
Interesting, we actually have a test that this should work: https://github.com/gradle/gradle/blob/b5097512d1152658f84b970984cfd81f0dc38994/subprojects/model-core/src/test/groovy/org/gradle/internal/reflect/annotations/impl/DefaultTypeAnnotationMetadataStoreTest.groovy#L207-L212

The Gradle code checks if the the generated getter(s) are annotated with `@Generated`. Could you point me to the source code where the properties are defined?

**Comment by aalmiray** [comment] 2019-10-23 12:09
Here it is https://github.com/aalmiray/jdeprscan-gradle-plugin/blob/master/src/main/groovy/org/kordamp/gradle/jdktools/JDeprScanReportTask.groovy#L31

Now that you mention the use of `@Generated` to detect this case I think the cause is an older version of Groovy. The latest release of this plugin was made with Gradle `4.10.2` which I suspect relies on a version of Groovy where `@Generated` was not attached to getters. Newer versions of Groovy do and it makes sense for Gradle `6`to pick them up correctly.

**Comment by wolfs** [comment] 2019-10-23 16:03
Is there any chance to detect the generated getters with older versions of Groovy?

**Comment by aalmiray** [comment] 2019-10-23 16:18
Alas no, there's no other way to detect that before Groovy 2.5.3 IIRC (when `@Generated` was introduced) and I think getters were correctly marked until 2.5.4.

**Comment by aalmiray** [comment] 2019-10-26 19:35
Fixed with release `0.5.0`.

**Closed as completed** 2019-10-26 19:35 UTC
Labels: enhancement

**Comment by boris-petrov** [comment] 2019-11-27 08:02
@aalmiray - i just saw that even with version `0.5.0` I get the last three deprecation warnings for each source set. Am I missing something or should we reopen this?

**Comment by aalmiray** [comment] 2019-11-28 15:54
@boris-petrov any chance you can share a small project reproducing the problem?

**Comment by boris-petrov** [comment] 2019-11-29 15:18
@aalmiray - I'll try in the next few days, yes. Thanks.

**Comment by aalmiray** [comment] 2019-11-30 22:50
AFAIK this plugin does not define additional sourcesets. Did you define a sourceSet with that name or do you happen to have applied another plugin that creates such sourcesets?

**Comment by boris-petrov** [comment] 2019-12-01 06:59
@aalmiray - OK, sorry, that was my mistake. I had the following configuration:

```gradle
def jdeprscanJdepsSourceSets = sourceSets.collect { it.name }

jdeprscanReport {
	sourceSets = jdeprscanJdepsSourceSets
	configurations = project.sourceSets.collectMany { [
		it.compileClasspathConfigurationName, it.compileOnlyConfigurationName,
		it.compileConfigurationName, it.runtimeConfigurationName, it.runtimeClasspathConfigurationName,
	] }
}
```

Because that way it was working fine. I obviously have to remove the `it.compileOnlyConfigurationName, it.compileConfigurationName, it.runtimeConfigurationName` part on Gradle 6.

Sorry for the confusion and thank you for the support!
